In [212]:
'''
Our KNN algorithm

'''
# imports go here
import pandas as pd
import numpy as np

In [255]:
'''
Part 1: Setting it all up
'''

# we will need a euclidean_distance_algorithm that takes in
# two numpy arrays, and calculates the 
# euclidean distance between them

def euclidean_distance(np1, np2):
    return np.sqrt(sum((np2 - np1)**2))
    



In [256]:
'''
Bring in the iris data from the web

iris_data ==
    2D numpy array of the four predictors of iris
        plus the species
'''

iris_data = pd.read_csv('https://raw.githubusercontent.com/sinanuozdemir/sfdat22/master/data/iris.csv')



In [257]:

# iris_data is a dataframe, but let's turn it into
# a 2D numpy array
# Hint: use .values to turn a dataframe into a 2d array

iris_data = iris_data.values
type(iris_data)

numpy.ndarray

In [258]:
# Question: in terms of machine learning:
#   a. the first four columns are called what? #predictors or independent variables
#   b. the species column is called what? #response or dependent variables

'''
array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       ... ...
       [6.2, 3.4, 5.4, 2.3, 'Iris-virginica'],
       [5.9, 3.0, 5.1, 1.8, 'Iris-virginica']], dtype=object)
'''

iris_data[0:10,:] #to show only first 10 rows of the result sets

predictors = iris_data[:,0:4]
response = iris_data[:, 4]
iris_data



array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [271]:
'''
Part 2: Predictions

Before we jump into making a general function,
let's try to predict 

unknown = [ 6.3,  3.1 ,  5.1,  2.4] with 3 neighbors
'''

# define our variables
unknown = [ 5.4,3.7 ,  1.5,  0.2]
k = 3
unknown = np.array(unknown) # converting from list to n-demionsional array
type(unknown)

numpy.ndarray

In [272]:
predictors

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [273]:
# Make a a list "distances" consisting of tuples
# Each tuple should be
# (euc_distance(unknown, data_point), species)
# for each data_point in iris_data
distances = []
'''
== [(4.4866468548349108, 'setosa'),
 (4.5276925690687078, 'setosa'),
 (4.6743983570080969, 'setosa'),
 ...
 (0.44721359549995821, 'virginica'),
 (0.72801098892805138, 'virginica')]

'''   

euc_dis = [euclidean_distance(x, unknown) for x in np.array(iris_data[:,0:4])]
response = iris_data[:, 4]
distances = zip(euc_dis, response)
distances



[(0.37416573867739483, 'Iris-setosa'),
 (0.86602540378443882, 'Iris-setosa'),
 (0.8831760866327848, 'Iris-setosa'),
 (1.0000000000000007, 'Iris-setosa'),
 (0.42426406871192884, 'Iris-setosa'),
 (0.34641016151377529, 'Iris-setosa'),
 (0.86602540378443937, 'Iris-setosa'),
 (0.50000000000000044, 'Iris-setosa'),
 (1.2845232578665131, 'Iris-setosa'),
 (0.78740078740118113, 'Iris-setosa'),
 (0.0, 'Iris-setosa'),
 (0.67823299831252748, 'Iris-setosa'),
 (0.93273790530888201, 'Iris-setosa'),
 (1.3674794331177347, 'Iris-setosa'),
 (0.58309518948452965, 'Iris-setosa'),
 (0.78740078740118125, 'Iris-setosa'),
 (0.34641016151377529, 'Iris-setosa'),
 (0.38729833462074237, 'Iris-setosa'),
 (0.38729833462074142, 'Iris-setosa'),
 (0.33166247903554053, 'Iris-setosa'),
 (0.36055512754639912, 'Iris-setosa'),
 (0.36055512754639957, 'Iris-setosa'),
 (0.94868329805051443, 'Iris-setosa'),
 (0.6164414002968982, 'Iris-setosa'),
 (0.78102496759066597, 'Iris-setosa'),
 (0.81240384046359637, 'Iris-setosa'),
 (0.547

In [274]:
# Grab the nearest k neighbors

# Now we need to take the most frequently occuring flower
# in those k neighbors
# To do this, Make a function that takes in a list, and returns the most commonly
# occuring object. If there is a tie, return either of them

# given a list l, this code will spit back the mode

from collections import Counter
list = [1,2,3,4,3,2,2,5,8,2,2,2,5,9,2,2,5,5,3,2]
def most_frequent(list):
    count = Counter()
    for i in list:
        count[i] += 1
    #return count
    return count.most_common(1)[0][0]
    #return 2 # == 2
    



In [275]:
most_frequent(list)

2

In [276]:
sorted(distances[0])
type(distances)



list

In [277]:
# Create a list called nearest with the K nearest neighbors
nearest = []
nearest = sorted(distances)[0:k]
nearest

[(0.0, 'Iris-setosa'),
 (0.10000000000000053, 'Iris-setosa'),
 (0.28284271247461928, 'Iris-setosa')]

In [278]:
# use it to find the most frequent occuring flower in nearest
# note that the species is in the 1th index
most_frequent([n[1] for n in nearest])

'Iris-setosa'

In [228]:
'''
Time to put it in a function so we 
can apply the prediction
to each row in our data set!
'''    
# will default to 3 neighbors
'''
    Input:
        unknown  == four attributes of an unknown flower
        k        == the number of neighbors used
    Output:
        A prediction of the species of flower (str)
        
        euclidean_distance = [euclidean_distance(x, unknown) for x in np.array(iris_data[:,0:4])]
response = iris_data[:, 4]
distances = zip(euclidean_distance, response)
distances
'''
def predict(unknown, k = 3):  
    # find the euclidean distance   
    #eucli_distance = []
    #predictors = iris_data[:,0:4]
    for x in predictors:
        #dist = euclidean_distance(unknown, x)
        eucli_distance = np.append(eucli_distance, euclidean_distance)
        distances = zip(eucli_distance, response)
    
    # find k-nearest neighbors
    nearest = sorted(distances)[0:k]
    #find most frequented neighbors
    flower_type = most_frequent([n[1] for n in nearest])
    return flower_type
    



In [318]:
def predict(unknown, k = 3):
    #find euclidean distance
    euc_dis1 = []
    for x in predictors:
        dist = euclidean_distance(x, unknown)
        euc_dis1 = np.append(euc_dis1, dist)
        distances = zip(euc_dis1, response)
    #find K nearest neighbor
    nearest = sorted(distances)[0:k]
    
    #find most common type
    common = most_frequent(nearest)
    
    #return the answer
    return common[1]

In [322]:
    
predict([ 6.9,  3.2,  5.7,  2.3], 3) # == 'virginica'

'Iris-virginica'

In [353]:
iris_data[:2]

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa']], dtype=object)

In [355]:
'''
Putting it all together
'''

# predict each row
# Note I use row[-1] because the last element of each row 
# is the actual species #row[:4]
predictions = np.array([predict(row[:4]) for row in iris_data])
predictions

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [337]:
# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

0.96666666666666667

In [356]:
# now with k == 5
predictions = np.array([predict(row[:4], k = 5) for row in iris_data])


# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

0.93999999999999995

In [339]:
# now with k == 2
predictions = np.array([predict(row[:4], k = 2) for row in iris_data])


# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

0.98666666666666669

In [341]:
# now with k == 1
predictions = np.array([predict(row[:4], k = 1) for row in iris_data])


# this is the last column of the iris_data
actual = np.array([row[-1] for row in iris_data])

# accuracy of the model
np.mean(predictions == actual)

#WHAAATTTTTT

1.0